services:
  - type: web
    name: bot-vip-telegram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WOOVI_APP_ID
        sync: false
      - key: CANAL_VIP_ID
        sync: false
      - key: ADMIN_ID
        sync: false